FROM node:20-alpine AS amd64-build
FROM arm64v8/node:20-alpine AS arm64-build
FROM ${TARGETARCH}-build AS build

ARG BUILD_TIMESTAMP
ARG BUILD_COMMIT_HASH
ARG BUILD_RELEASE_VERSION

# UI feature flags — override at build time with:
#   docker build --build-arg REACT_APP_FEATURE_DAG=0 .
# See docs/feature-flags.md for full list and descriptions.
ARG REACT_APP_FEATURE_DAG=1
ARG REACT_APP_FEATURE_RUN_GROUPS=0
ARG REACT_APP_FEATURE_TASK_METADATA=1
ARG REACT_APP_FEATURE_TIMELINE_MINIMAP=1
ARG REACT_APP_FEATURE_ARTIFACT_TABLE=0
ARG REACT_APP_FEATURE_ARTIFACT_SEARCH=0
ARG REACT_APP_FEATURE_FOREACH_VAR_SEARCH=0
ARG REACT_APP_FEATURE_DEBUG_VIEW=1
ARG REACT_APP_FEATURE_CARDS=1
ARG REACT_APP_FEATURE_HIDE_LOGO=0
ARG REACT_APP_FEATURE_HIDE_HOME_BUTTON=0
ARG REACT_APP_FEATURE_HIDE_STATUS_FILTERS=0
ARG REACT_APP_FEATURE_HIDE_TABLE_HEADER=0
ARG REACT_APP_FEATURE_HIDE_QUICK_LINKS=0
ARG REACT_APP_FEATURE_HIDE_CONNECTION_STATUS=0

ENV REACT_APP_BUILD_TIMESTAMP=$BUILD_TIMESTAMP
ENV REACT_APP_COMMIT_HASH=$BUILD_COMMIT_HASH
ENV REACT_APP_RELEASE_VERSION=$BUILD_RELEASE_VERSION
ENV REACT_APP_FEATURE_DAG=$REACT_APP_FEATURE_DAG
ENV REACT_APP_FEATURE_RUN_GROUPS=$REACT_APP_FEATURE_RUN_GROUPS
ENV REACT_APP_FEATURE_TASK_METADATA=$REACT_APP_FEATURE_TASK_METADATA
ENV REACT_APP_FEATURE_TIMELINE_MINIMAP=$REACT_APP_FEATURE_TIMELINE_MINIMAP
ENV REACT_APP_FEATURE_ARTIFACT_TABLE=$REACT_APP_FEATURE_ARTIFACT_TABLE
ENV REACT_APP_FEATURE_ARTIFACT_SEARCH=$REACT_APP_FEATURE_ARTIFACT_SEARCH
ENV REACT_APP_FEATURE_FOREACH_VAR_SEARCH=$REACT_APP_FEATURE_FOREACH_VAR_SEARCH
ENV REACT_APP_FEATURE_DEBUG_VIEW=$REACT_APP_FEATURE_DEBUG_VIEW
ENV REACT_APP_FEATURE_CARDS=$REACT_APP_FEATURE_CARDS
ENV REACT_APP_FEATURE_HIDE_LOGO=$REACT_APP_FEATURE_HIDE_LOGO
ENV REACT_APP_FEATURE_HIDE_HOME_BUTTON=$REACT_APP_FEATURE_HIDE_HOME_BUTTON
ENV REACT_APP_FEATURE_HIDE_STATUS_FILTERS=$REACT_APP_FEATURE_HIDE_STATUS_FILTERS
ENV REACT_APP_FEATURE_HIDE_TABLE_HEADER=$REACT_APP_FEATURE_HIDE_TABLE_HEADER
ENV REACT_APP_FEATURE_HIDE_QUICK_LINKS=$REACT_APP_FEATURE_HIDE_QUICK_LINKS
ENV REACT_APP_FEATURE_HIDE_CONNECTION_STATUS=$REACT_APP_FEATURE_HIDE_CONNECTION_STATUS

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
# timeout is a required fix for arm64 builds
RUN yarn --frozen-lockfile --network-timeout 1000000

COPY . ./
RUN yarn build

# https://github.com/docker-library/official-images#architectures-other-than-amd64
FROM nginx AS amd64-nginx
FROM arm64v8/nginx AS arm64-nginx
FROM ${TARGETARCH}-nginx

ENV PORT=3000
ENV METAFLOW_SERVICE=/api

# nginx.conf.template environment variables
# for injecting content to index.html during runtime
ENV METAFLOW_HEAD=''
ENV METAFLOW_BODY_BEFORE=''
ENV METAFLOW_BODY_AFTER=''
ENV MF_DEFAULT_TIME_FILTER_DAYS=''
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/templates/default.conf.template
