name: Package features

on:
  push:
    tags:
      - '*' # Package on all tag pushes

jobs:
  package-features:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: true

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}-features" >> $GITHUB_ENV

      - run: yarn --frozen-lockfile
      - name: Build application
        run: yarn build
        env:
          REACT_APP_RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          REACT_APP_COMMIT_HASH: ${{ github.sha }}
          REACT_APP_FEATURE_DAG: 0 # Disable DAG view
          REACT_APP_FEATURE_RUN_GROUPS: 0 # Disable grouping
          REACT_APP_FEATURE_TASK_METADATA: 0 # Disable grouping
          REACT_APP_FEATURE_TIMELINE_MINIMAP: 0 # Disable grouping

      - uses: actions/upload-artifact@v2
        with:
          name: metaflow-ui-${{ env.RELEASE_VERSION }}
          path: ./build
